### PR TITLE
Documentation for FlexRex integration (see #663)

### PR DESCRIPTION
**Pull request by vladimirvivien**
This commit adds documentation for FlexRex integration and includes
examples of persistent volume, persitent volume claim, and pods.

### CODE REVIEW

**Comment by clintonskitson** [comment]
Would it make sense to include the parameters such as forceAttach?

**Comment by vladimirvivien** [comment]
@clintonskitson the YAML includes `forceAttach` params. Do you mean including somewhere else ?

**Comment by cduchesne** [comment]
I agree that a table describing the options could be helpful.

**Comment by vladimirvivien** [comment]
@clintonskitson @cduchesne doesnt `forceAttach` have a universal meaning in REX-Ray ?

**Comment by cduchesne** [comment]
@vladimirvivien yes but good to connect forceAttach and forceAttach delay to what they mean here as well. In REX-Ray we have a --force flag available to the attach command, although this may not always be clearly visible to some. We definitely have no concept of the forceAttachDelay yet.

**Comment by vladimirvivien** [comment]
@clintonskitson @cduchesne added doc for options, update to the pre-reqs.

**Comment by vladimirvivien** [comment]
@cduchesne PTAL

**Pull request merged**
