### PR TITLE
Added fixes to enable custom s3 endpoints for s3fs

### PR DESCRIPTION
**Pull request by dahendel**
Added ConfigS3FSEndpoint config key and Endpoint constant. This enables adding a self hosted s3 endpoint.

Example Config:
```
libstorage:
  service: s3fs
  integration:
    volume:
      operations:
        create:
          default:
            size: 100
        mount:
          rootPath: /rexray 
s3fs:
  accessKey: AccessKey
  secretKey: SecretKey
  endpoint: CustomS3Url
  options:
  - url=CustomS3Url
  - use_path_request_style
  - allow_other
  - nonempty
```

### CODE REVIEW

**Comment by clintkitson** [comment]
@dahendel Can you review the PR for extra files that may not be needed? This looks to be a simple config update, but it also looks like there were extra dependencies that might have been introduced during troubleshooting?

**Comment by dahendel** [comment]
@clintkitson will do. Working on it now.

**Comment by dahendel** [comment]
@clintkitson Fixed.

**Comment by akutz** [comment]
Hi @dahendel,

I'll take a closer look at this later today or early tomorrow. My concern is that it could have possible issues akin to the problems found in codedellemc/libstorage#518. The challenge is when the client sends region information that could be in conflict with the endpoint information defined on the server-side.

**Comment by akutz** [comment]
Hi @dahendel,

Thank you for this. I've reviewed this and it looks very logical. Thank you again.

**Comment by dahendel** [comment]
Thanks, glad I could help out.

**Comment by harshavardhana** [comment]
Any ETA when this will be released? docs are not updated like there was no new ENV added for `docker plugin install rexray/s3fs` ?

**Comment by harshavardhana** [comment]
I see now this is already out in https://github.com/codedellemc/rexray/releases/tag/v0.10.1

**Comment by prein** [comment]
New S3FS_ENDPOINT variable added to docker plugin would be much appreciated.

**Comment by dahendel** [comment]
@prein there is a PR for it #1042

**Pull request merged**
