### PR TITLE
Fixing typo: archtitecture -> architecture

### PR DESCRIPTION
**Pull request by alexellis**
Thought you would want to fix this.

### CODE REVIEW

**Comment by akutz** [comment]
Hi @alexellis,

Thanks! Could you please sign the CLA so I am able to merge this? Thank you again.

**Comment by codenrhoden** [comment]
@alexellis Any update on signing the CLA?

**Comment by alexellis** [comment]
I'll be able to do this next week due to limited internet access.

**Comment by akutz** [comment]
I'd merge it except it includes two commits instead of one. I may simply handle this manually for you @alexellis.

**Comment by akutz** [comment]
Closing with 74c58d2706818d1ff3c391cc49010511d27b118c.

**Pull request closed without merging**
